apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapp-backend
  template:
    metadata:
      labels:
        app: dapp-backend
    spec:
      containers:
      - name: dapp-backend
        image: criptoland.azurecr.io/dappbackend
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: dapp-backend  
spec: 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: dapp-backend